config/routes.rb
Rails.application.routes.draw do
  mount SolidusPaypalCommercePlatform::Engine, at: '/solidus_paypal_commerce_platform'
  root to: 'home#index'

  devise_for(:user, {
    class_name: 'Spree::User',
    singular: :spree_user,
    controllers: {
      sessions: 'user_sessions',
      registrations: 'user_registrations',
      passwords: 'user_passwords',
      confirmations: 'user_confirmations'
    },
    skip: [:unlocks, :omniauth_callbacks],
    path_names: { sign_out: 'logout' }
  })

  resources :users, only: [:edit, :update]

  devise_scope :spree_user do
    get '/login', to: 'user_sessions#new', as: :login
    post '/login', to: 'user_sessions#create', as: :create_new_session
    match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
    get '/signup', to: 'user_registrations#new', as: :signup
    post '/signup', to: 'user_registrations#create', as: :registration
    get '/password/recover', to: 'user_passwords#new', as: :recover_password
    post '/password/recover', to: 'user_passwords#create', as: :reset_password
    get '/password/change', to: 'user_passwords#edit', as: :edit_password
    put '/password/change', to: 'user_passwords#update', as: :update_password
    get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
  end

  resource :account, controller: 'users'

  resources :products, only: [:index, :show]

  resources :autocomplete_results, only: :index

  resources :cart_line_items, only: :create

  get '/locale/set', to: 'locale#set'
  post '/locale/set', to: 'locale#set', as: :select_locale

  resource :checkout_session, only: :new
  resource :checkout_guest_session, only: :create

  # non-restful checkout stuff
  patch '/checkout/update/:state', to: 'checkouts#update', as: :update_checkout
  get '/checkout/:state', to: 'checkouts#edit', as: :checkout_state
  get '/checkout', to: 'checkouts#edit', as: :checkout

  get '/orders/:id/token/:token' => 'orders#show', as: :token_order

  resources :orders, only: :show do
    resources :coupon_codes, only: :create
  end

  resource :cart, only: [:show, :update] do
    put 'empty'
  end

  # route globbing for pretty nested taxon and product paths
  get '/t/*id', to: 'taxons#show', as: :nested_taxons

  get '/unauthorized', to: 'home#unauthorized', as: :unauthorized
  get '/cart_link', to: 'store#cart_link', as: :cart_link

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/autocomplete_results_controller.rb
# frozen_string_literal: true

class AutocompleteResultsController < StoreController
  def index
    respond_to do |format|
      format.html { redirect_to products_path(keywords: params[:keywords]) }
      format.turbo_stream { load_results }
    end
  end

  private

  def load_results
    @results ||= begin
      results = {}
      results[:products] = autocomplete_products
      results[:taxons] = autocomplete_taxons
      results
    end
  end

  def autocomplete_products
    if params[:keywords].present?
      searcher = build_searcher(params.merge(per_page: 5))
      searcher.retrieve_products
    else
      Spree::Product.none
    end
  end

  def autocomplete_taxons
    if params[:keywords].present?
      Spree::Taxon
        .where(Spree::Taxon.arel_table[:name].matches("%#{params[:keywords]}%"))
        .limit(5)
    else
      Spree::Taxon.none
    end
  end
end

app/views/autocomplete_results/_autocomplete_results.html.erb
<ul class="autocomplete-results__list">
  <li class="autocomplete-results__title">
    <%= t('spree.products') %>
  </li>

  <% if results[:products].any? %>
    <% results[:products].each do |product| %>
      <li class="autocomplete-results__item"
          data-search-target="result">
        <%= link_to product.name, product_path(product) %>
      </li>
    <% end %>

    <li class="autocomplete-results__item"
        data-search-target="result">
      <%= link_to "See all results", products_path(keywords: params[:keywords]) %>
    </li>
  <% else %>
    <li class="autocomplete-results__item autocomplete-results__item--empty">No results</li>
  <% end %>

  <li class="autocomplete-results__title">
    <%= t('spree.taxons') %>
  </li>

  <% if results[:taxons].any? %>
    <% results[:taxons].each do |taxon| %>
      <li class="autocomplete-results__item"
          data-search-target="result">
        <%= link_to taxon.name, nested_taxons_path(taxon) %>
      </li>
    <% end %>
  <% else %>
    <li class="autocomplete-results__item autocomplete-results__item--empty">No results</li>
  <% end %>
</ul>

app/views/autocomplete_results/index.turbo_stream.erb
<%= turbo_stream.replace 'autocomplete-results' do %>
  <div id="autocomplete-results" class="autocomplete-results" data-search-target="results">
    <%= render 'autocomplete_results', results: @results %>
  </div>
<% end %>